typography_spectrum: 0.009658073773607612
content_rating:
  adult: false
color:
  brandStrength: 0.08734407369047403
  lightness: 0.7664613977540284
  saturation: 0.09904330223798752
  rhythmicContrast: 0.7134880688972771
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/9cb3c7a0-e510-4e9b-9435-c0798dc43261.jpg
  appId: 'https://www.facebook.com/IgaKuriataPhotography/'
  type: 'https://www.facebook.com/IgaKuriataPhotography/'
layout_spectrum: 0.7780394253786653
author:
  name: iga kuriata
  email: igakuriata@outlook.com
  url: 'https://www.facebook.com/IgaKuriataPhotography/'
name: iga kuriata photography
navigation:
  - name: Moesgaard Colloseum
    id: 146fb633-6114-437a-9150-6fcbcde7c85b
    type: content
  - name: Gladiators
    id: baeab329-c003-4797-b54f-c55d4b9877ae
    type: content
  - name: okok
    id: 9b6a7a73-b0f8-4fe8-999b-217016f082d4
    type: content
  - name: My first post
    id: 15a64454-cf80-499a-baba-83ad81e70b20
    type: content
  - name: Test 2
    id: 3731fc38-f3f5-4446-be7b-943909b9666f
    type: content
  - name: yoyo
    id: 49eaf64a-9543-4d35-9b76-b1bb3978ac63
    type: content
  - name: html
    id: ff8b33af-9952-416b-947f-8aaea56ccddc
    type: content
purpose:
  - type: contact
    url: 'tel:004552692616'
    label: 004552692616
  - type: contact
    url: 'mailto:igakuriata@outlook.com'
    label: Contact me
